# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 600d16dab4e96ede1bc25e1b2bca6dfe9cb01d8572710c260e5cc43ea58d7eeab9bab7d32c5cb7c5c2f05ceacdd7aa43524c7a00a0c6c081ab4d6450fc8107d2

test:
  secret_key_base: 05536431e8b8368e4c08cfe10bb77153258fc712cd2d0de1669e70c3826ed457eb94c7a72675c9655cf00ffcde9f9dbb59fb86029076151b217e8fe9083ee4d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
